### PR TITLE
Add boba to toolbox

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Review by jaspermayone — APPROVED** [review]
LGTM!

**Comment by jaspermayone** [comment]
CleanShot 2024-04-22 at 17 40 02@2x
@maxwofford fix your icon!

**Comment by maxwofford** [comment]
This wasn't supposed to be merged yet! I'm still deciding on the right icon to use

**Comment by jaspermayone** [comment]
AH! Sorry, was cleaning and figured it was ready.

**Pull request merged**
