### PR TITLE
Add HCB

### PR DESCRIPTION
**Pull request by jaspermayone**

### CODE REVIEW

**Comment by maxwofford** [comment]
Looks like this merge broke the build!

**Comment by maxwofford** [comment]
Missing comma out here https://github.com/hackclub/toolbox/pull/47/files#diff-41c0d7470bfc7b681a2074bb6c8e6d8356b7cfd44e45e8b0d41cce661ea7b982R121-R122

**Comment by jaspermayone** [comment]
oh i love breaking things

**Comment by jaspermayone** [comment]
will pr a fix rn

**Comment by jaspermayone** [comment]
oh you made one!

**Pull request merged**
